### ISSUE TITLE
Discrepancy between overview's dot product instructions and tests

### ISSUE THREAD

**Issue by alexcrichton** [WebAssembly/relaxed-simd#117]
Currently in the overview two dot product instructions are specified:

* `i16x8.relaxed_dot_i8x16_i7x16_s`
* `i32x4.relaxed_dot_i8x16_i7x16_add_s`

but [in the tests](https://github.com/WebAssembly/relaxed-simd/blob/95678a9f6fd9575584b6c39e760179b97c2e7432/test/core/relaxed-simd/relaxed_dot_product.wast#L4-L6) the names of the instructions drop the `relaxed_` prefix on the instruction name and additionally still have `f32x4.relaxed_dot_bf16x8_add_f32x4` as an instruction to test. Was the f32x4 instruction removed from the proposal and forgotten to have tests removed? Or the other way around where it was added but not added to the overview?

**Comment by Maratyszcza** [comment]
`f32x4.relaxed_dot_bf16x8_add_f32x4` was removed. `relaxed_` was added to all instruction names, but probably this change missed the tests.

**Comment by ngzhian** [comment]
This is now fixed.
