### ISSUE TITLE
How can fpenv be used?

### ISSUE THREAD

**Issue by ngzhian** [WebAssembly/relaxed-simd#19]
Given the current `fpenv` mechanism described in https://github.com/WebAssembly/relaxed-simd/blob/main/proposals/relaxed-simd/Overview.md#consistency I'm wondering how source languages (C/C++/Rust) will be able to use it, how can they specify that the `fpenv` should be the same between modules.

@sunfishcode do you have thoughts on this?

**Comment by sunfishcode** [comment]
I imagine toolchains will emit the `fpenv` value and the imports and exports automatically, as needed, similar to how eg. a function table is automatically included in programs that need it. It would make sense for the foreseeable future to have a toolchain convention that modules have at most one `fpenv`, so compiled code could always rely on the index being 0, and there'd be no need for relocations.

**Comment by tlively** [comment]
Would it ever make sense or be necessary for `fpenv`s to be declared or used in source code? Will there ever be a need for C/C++/Rust to have language extensions for them?

**Comment by sunfishcode** [comment]
I imagine that in most cases, modules will want to share their fpenv if they share their memory. So traditional C/C++/Rust use cases would just have a single `fpenv` shared across all the C/C++/Rust code, just as they share their memory.

The places I expect this will get introducing is shared-nothing module boundaries. The APIs for these will sometimes be defined with external tooling (eg. witx bindings generators), and sometimes with language extensions, depending on the toolchain and the use case. I imagine `fpenv` linkage would be defined in the same ways. So yes, it could involve language extensions, but only in the case where the language already has language extensions to describe shared-nothing APIs.

**Comment by sunfishcode** [comment]
One observation, after today's meeting: `qfma` nondeterminism doesn't just come from hardware; it can come from compilers too.

Consider code like this:
```
   let t0 = qfma(a, x, b0);
   let t1 = qfma(a, x, b1);
```
Even on a single CPU, a compiler has multiple choices:
 - two fma instructions
 - one multiply (`a * x`) and two adds

And, the choice of which to do might depend on the surrounding code. Perhaps two `fma` instructions are faster for straight-line code, but perhaps `a * b` is loop-invariant, and can be hoisted, leaving two adds in the loop, which is cheaper than two fmas. This means compilers can make different choices for how to implement `qfma` *even within the same function*. I've seen this happen in real-world applications, where lines that should be smooth have discontinuities, even when all the code is running on the same architecture.

**Comment by Maratyszcza** [comment]
@sunfishcode Note that for `qfma` instructions in Relaxed SIMD we mandate that compiler either always lower it to FMA form, or always lower it to non-FMA form.

It is true that compilers from high-level languages (e.g. C/C++) to Relaxed SIMD instructions may selectively fuse multiply + add into `qfma`. The behavior when targeting Relaxed SIMD is similar to native instruction sets, and compilers already have flags in place to control it.

**Comment by sunfishcode** [comment]
The question is, how "always" is "always"? ;-) Two expressions in the same function? Two functions in the same module? Two instances of the same module? Two instances within a store? Two instances across different stores? All instances ever? `fpenv` avoids the need to guess, and makes the relationships explicit.

**Comment by penzn** [comment]
> Consider code like this:
> 
> ```
>    let t0 = qfma(a, x, b0);
>    let t1 = qfma(a, x, b1);
> ```
> 
> Even on a single CPU, a compiler has multiple choices:
> 
> * two fma instructions
> * one multiply (`a * x`) and two adds

Which compiler does this in practice? It's true that multiply and add get fused into FMA, but I haven't seen them (and most of other intrinsics TBH) get split out into individual operations which then get reordered.

**Comment by tlively** [comment]
I thought that leaving a zero byte as a placeholder for a future `fpenv` extension was an interesting new idea from this morning's meeting. @sunfishcode, do you have plans to make use of `fpenv` in the near future? If no one has such concrete plans, perhaps we can leave it to the future and work out in the spec a good way to define the scope/lifetime in which the nondeterministic behavior must be fixed, as @conrad-watt suggested.

**Comment by sunfishcode** [comment]
@tlively I am hoping to preserve the property that we can link and split wasm modules without changing their semantics. A 0 byte does not seem to achieve this. See [here] for more discussion.

@penzn The compiler I saw do this was a GPU compiler, and I'm aware that wasm isn't great for GPUs today, but my point is that compilers have real reasons to want to do this, and if we don't want them to do it, we should say so in the spec.

[here]: https://github.com/WebAssembly/relaxed-simd/issues/38#issuecomment-929581009

**Comment by zeux** [comment]
I feel like for qfma to be maximally useful in practice, the lowering must be consistent across all individual instructions, at least within a single module. The same is likely true of other instructions like reciprocal approximations; extra non-determinism is likely to rarely be useful for optimization purposes and almost always be harmful for consistency / ease of use.

With that in mind, and the fact that in practice, what will happen is that the lowering will depend on the hardware the code is running on and the version of the VM, do we need fpenv at all?

One strawman idea is that we could state that:
- Engines must be deterministic within a module
- Engine must be deterministic across modules that are linked together (aka module A that imports module B, regardless of what the import is)

This feels like it sufficiently addresses the need for splitting and doesn't complicate the proposal with fpenv.

**Comment by penzn** [comment]
I understand that @sunfishcode is going to expand on this, but I am curious about a couple things I feel we did not cover thoroughly during discussion in the call (#37).

Firstly, what would be the visibility on the production side? Can users or tools interact with `fpenv` (and if - how)? 

Some precedents from other runtime systems (managed or otherwise) would be helpful as well.

**Comment by ngzhian** [comment]
> Is it actually true that all relaxed operators will be deterministic up to the environment parameter, or might some still have multiple possible outcomes (e.g. wrt NaNs)?

Yea the usual NaN propagation behaviors w.r.t. float operations still happens:

- relaxed swizzle, i32x4_trunc_f32x4, laneselect are all integer ops
- relaxed f32x4/f64x2 min/max will have the same effect as NaN behaviors as normal float min/max
- ditto for relaxed fma

So perhaps saying "fixed to a particular deterministic operation" is too strict

> Some operators are relaxed (TODO find a better adjective), because the result depends on the underlying execution environment (such as hardware support). Each relaxed operator can be thought of as a family of operators that is fixed to one particular operator as determined by the current execution context. The fixed operator itself can be non-deterministic (because they can return different NaN values).

**Comment by ngzhian** [comment]
Translating
> Technically, each such operator produces a fixed-size list of sets of allowed results.

into the formal notation (using relaxed fma as an example)

```
relaxed fma_N(z_1, z_2, z_3) = [
  fadd_N(z_1, fmul_N(z_2, z_3), 
  demote_{2N,N}(fadd_2N(promote_2N(z_1),
                        fmul_2N(promote_2N(z_2), promote_2N(z_3))) ]
```

Looks about right?

> For qfma, it's desirable that the the implementation be always a*x+b or always FMA(a,x,b) and never a mix of the two, even if the mix would be deterministic on a given host, to avoid surprising discontinuities and asymmetries. Is this what the "list of sets" phrase refers to?

I think this is captured by:

> For every execution of the operator in the same environment, only values from the set at the same position in that list are returned

**Comment by ngzhian** [comment]
Closing this since we do not have an explicity fpenv anymore.
