### ISSUE TITLE
Tweak prototype spec text to address issues raised in Phase 2 poll

### ISSUE THREAD

**Issue by ngzhian** [WebAssembly/relaxed-simd#53]
Suggested spec text can be found in this commit https://github.com/ngzhian/relaxed-simd/commit/21229c0ef509d5b5d3e22111f82381af2cbe079a and previewed at https://www.ngzhian.com/relaxed-simd/core/exec/numerics.html#relaxed-operations

The comments we got at the [phase 2 poll](https://github.com/WebAssembly/meetings/blob/main/main/2021/CG-11-09.md#update-on-relaxed-simd-fpenv-discussions-and-poll-for-phase-2-zhi-an-ng-15-min) is summarized in https://github.com/WebAssembly/relaxed-simd/issues/38#issuecomment-964460043 and comments following that:

- [x] the choice of fixed projection means that the individual cases for an instruction are correlated, e.g. for relaxed min we cannot have the case where you return the the first operand when either operand is nan (like x86 but returning first operand)
- [x] the instructions are using set notations, it should be a list of sets
- [ ] consistency between similar ops, multiply add and multiply subtract, for example

This issue tracks work required to update the spec text.

**Comment by ngzhian** [comment]
Updated to use list notation, see https://www.ngzhian.com/relaxed-simd/core/exec/numerics.html#relaxed-operations.
Consistency between fma/fms resolved by defining fms in terms of fma (with 3rd input negated).

We still don't have consistency between min/max, but that's ok, @Maratyszcza mentioned something about giving the implementation the freedom for optimization here (but it wasn't captured in the meeting notes, if you can elaborate a bit more that will be great).

For the first item, choice of fixed projection, we can add 1 more case for min/max to allow for the case where we return first operand where either operand is a nan. Although none of the architectures I've looked at does this, we can add it as a reasonable implementation.

**Comment by lars-t-hansen** [comment]
Nit: Rightparen missing in defns of relaxed_fma and relaxed_fms.

**Comment by ngzhian** [comment]
> Nit: Rightparen missing in defns of relaxed_fma and relaxed_fms.

Fixed, thanks!

**Comment by ngzhian** [comment]
Tracking Phase 3 poll feedback on spec text in #71
