### ISSUE TITLE
Test infrastructure updates required to support testing relaxed SIMD instructions

### ISSUE THREAD

**Issue by ngzhian** [WebAssembly/relaxed-simd#54]
Relaxed SIMD instructions can return any value from a specified set of allowed values depending on the execution environment. The test scripts support `assert_return` which checks that a set of `actions` lead to certain `results`.

We need a way to specify that we expect a result is one of a set of allowable results, something like:

`(assert_one_of actions (result*)) ; assert that actions lead to a single result, which can be any one of results*`

We *might* want to generalize this to allow matching multiple results to multiple sets of allowable results, but that seems unnecessary for now.

Note that the test interpreter will probably choose 1 way of implementing relaxed SIMD instructions, but this is more about generating JS tests, which engines can run on different environments, and get good test coverage and correct results.

@rossberg for comments

**Comment by abrown** [comment]
cc: @alexcrichton (this may involve changes to the Rust `wast` crate).

**Comment by rossberg** [comment]
The threads proposal repo already adds an `(either <result>+)` result pattern, like [here](https://github.com/WebAssembly/threads/blob/85b562cd6805947876ec5e8b975ab0127c55a0a2/test/core/thread.wast#L24). Any reason not to reuse that?
