### ISSUE TITLE
Tracking issue for updating binary opcodes

### ISSUE THREAD

**Issue by ngzhian** [WebAssembly/relaxed-simd#74]
This issue tracks the status of updating relaxed-simd instruction binary opcodes to match the [overview](https://github.com/WebAssembly/relaxed-simd/blob/main/proposals/relaxed-simd/Overview.md#binary-format).

- [x] V8
- [x] Firefox
- [x] Emscripten/LLVM
- [x] Binaryen
- [x] Spec interpreter

To add new engines/toolchains to track, please comment.

**Comment by ngzhian** [comment]
@dtig @tlively fyi

**Comment by tlively** [comment]
LLVM patch up for review: https://reviews.llvm.org/D125726

**Comment by dtig** [comment]
V8 patch landed last week: https://chromium-review.googlesource.com/c/v8/v8/+/3625835. Should be available in canary by now.

**Comment by ngzhian** [comment]
@tlively Binaryen will need to be updated too right?

**Comment by tlively** [comment]
Yes, that's right. I'll try to update it soon.

**Comment by tlively** [comment]
Binaryen updated in https://github.com/WebAssembly/binaryen/commit/b7a93cca37d2253ef36e4cc63ef38c3647404597.

I also have a patch up for review adding the final instructions in LLVM: https://reviews.llvm.org/D127170.
