### ISSUE TITLE
Missing tests?

### ISSUE THREAD

**Issue by eqrion** [WebAssembly/relaxed-simd#94]
We were looking at using the tests [1] for this proposal in SpiderMonkey and it looks like some tests may be missing for some instructions.

I don't see any tests for:
```
1. i16x8.dot_i8x16_i7x16_s
2. i32x4.dot_i8x16_i7x16_add_s
3. f32x4.relaxed_dot_bf16x8_add_f32x4
```

[1] https://github.com/WebAssembly/relaxed-simd/tree/main/test/core/relaxed-simd

**Comment by ngzhian** [comment]
You're right, these are newer instructions which I haven't added tests for. I'll be adding them soon.

**Comment by ngzhian** [comment]
Added:

1. i16x8.dot_i8x16_i7x16_s
2. i32x4.dot_i8x16_i7x16_add_s

Not added f32x4.relaxed_dot_bf16x8_add_f32x4 as instruction was removed from proposal #106
